=== UladzimirHerman/EPAM-Training/task04/resources/tariff.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tariffs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tariff" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:string" name="description"/>
                            <xs:element name="in_archive">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="true"/>
                                        <xs:enumeration value="false"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:float" name="subscription_fee"/>
                            <xs:element type="xs:byte" name="num_subscriber"/>
                            <xs:element type="xs:short" name="free_minute"/>
                            <xs:element type="xs:float" name="cost_minute"/>
                            <xs:element type="xs:byte" name="free_sms"/>
                            <xs:element type="xs:float" name="cost_sms"/>
                            <xs:element name="free_internet">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:short">
                                            <xs:attribute type="xs:string" name="unit" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:float" name="cost_internet"/>
                            <xs:element type="xs:short" name="free_colleague_minute" minOccurs="0"/>
                            <xs:element type="xs:float" name="cost_colleague_minute" minOccurs="0"/>
                            <xs:element type="xs:byte" name="free_international_minute" minOccurs="0"/>
                            <xs:element type="xs:float" name="cost_international_minute" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:ID">
                                    <xs:pattern value="T\d{3}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute type="xs:string" name="currency" use="required"/>
                        <xs:attribute name="type" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="corporate_tariff"/>
                                    <xs:enumeration value="personal_tariff"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== UladzimirHerman/EPAM-Training/task04/resources/tariff.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="tariff.xsd">
    <tariff id="T101" currency="USD" type="corporate_tariff">
        <name>Corporation</name>
        <description>Maintain communication between colleagues</description>
        <in_archive>false</in_archive>
        <subscription_fee>50</subscription_fee>
        <num_subscriber>5</num_subscriber>
        <free_minute>100</free_minute>
        <cost_minute>0.03</cost_minute>
        <free_sms>0</free_sms>
        <cost_sms>0.04</cost_sms>
        <free_internet unit="MB">1024</free_internet>
        <cost_internet>0.01</cost_internet>
        <free_colleague_minute>10000</free_colleague_minute>
        <cost_colleague_minute>0.05</cost_colleague_minute>
    </tariff>
    <tariff id="T201" currency="USD" type="personal_tariff">
        <name>Comfort</name>
        <description>For a better life</description>
        <in_archive>true</in_archive>
        <subscription_fee>11.5</subscription_fee>
        <num_subscriber>7</num_subscriber>
        <free_minute>500</free_minute>
        <cost_minute>0.07</cost_minute>
        <free_sms>50</free_sms>
        <cost_sms>0.05</cost_sms>
        <free_internet unit="MB">512</free_internet>
        <cost_internet>0.08</cost_internet>
        <free_international_minute>10</free_international_minute>
        <cost_international_minute>0.95</cost_international_minute>
    </tariff>
    <tariff id="T202" currency="USD" type="personal_tariff">
        <name>Online</name>
        <description>For Internet users</description>
        <in_archive>false</in_archive>
        <subscription_fee>12</subscription_fee>
        <num_subscriber>14</num_subscriber>
        <free_minute>100</free_minute>
        <cost_minute>0.08</cost_minute>
        <free_sms>0</free_sms>
        <cost_sms>0.01</cost_sms>
        <free_internet unit="MB">5120</free_internet>
        <cost_internet>0.02</cost_internet>
        <free_international_minute>0</free_international_minute>
        <cost_international_minute>0.8</cost_international_minute>
    </tariff>
</tariffs>
